[bot]
server: localhost
chat_id: 115254279
bot_token: 8841196518:AAFS0ezZoQMs6405fim5EGq5NMJQW9uP9Nw #1991994117:AAHFi6jJjIGM66FvCS8tcpoc4xuXF3kFPeE
#log_path: /home/pi/klipper_logs

[camera]
host: http://localhost:8080/?action=stream
fps: 60
video_duration: 10
video_buffer_size: 5
#: 180


[timelapse]
cleanup: true
height: 0.2
time: 60
target_fps: 60
min_lapse_duration: 15
max_lapse_duration: 15
last_frame_duration: 1




